sonar:
    script: ./build.sh && sonar-scanner -Dsonar.projectKey=flatcraft_PEL19_$CI_PROJECT_NAMESPACE 
    stage: build
    tags:
     - sonar
     - java
    artifacts:
     paths:
        - flatcraft.jar
