sonar:
    script: ./build.sh && sonar-scanner -Dsonar.login=$SONARTOKEN -Dsonar.projectKey=flatcraft_2020_$CI_PROJECT_NAMESPACE 
    stage: build
    tags:
     - sonar
     - java
    artifacts:
     paths:
        - flatcraft.jar
